project:
  type: website

website:
  navbar:
    left:
    - href: index.qmd
      text: Home
    - text: "Proposal"
      href: "Proposal/Proposal.html"
    right:
      - about.qmd

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

