project:
  type: website

website:
  navbar:
    left:
    - href: index.qmd
      text: Home
    - text: "Methodology"
      href: "methodology/methodology.html"
    - text: "User Guide"
      href: "userguide/userguide.html"
    - text: "Poster"
      href: "poster/poster.html"
    right:
      - about.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

