project:
  type: website

website:
  navbar:
    left:
    - href: index.qmd
      text: Home
    - text: "Methodology"
      href: "methodology/methodology.html"
    - text: "User Guide"
      href: "userguide/userguide.html"
    - text: "Poster"
      href: "poster/poster.pdf"
    - text: "The App"
      href: "https://mllaw319.shinyapps.io/swim_analytica/"
    right:
      - about.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

