project:
  type: website

website:
  title: "GroupProject"
  navbar:
    left:
    - text: "The Beginning"
      menu:
        - text: "Project Proposal"
          href: "Proposal/Proposal.html"
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

